src/Entity/Characters.php
<?php

namespace App\Entity;

use App\Repository\CharactersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CharactersRepository::class)]
class Characters
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $Name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Planet = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $SuperPower = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $BirthDate = null;

    #[ORM\ManyToMany(targetEntity: Weakness::class, inversedBy: 'weaknesses')]
    private Collection $weaknesses;



    public function __construct()
    {
        $this->weaknesses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): static
    {
        $this->Name = $Name;

        return $this;
    }

    public function getPlanet(): ?string
    {
        return $this->Planet;
    }

    public function setPlanet(?string $Planet): static
    {
        $this->Planet = $Planet;

        return $this;
    }
    public function getSuperPower(): ?string
    {
        return $this->SuperPower;
    }

    public function setSuperPower(?string $SuperPower): static
    {
        $this->SuperPower = $SuperPower;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->BirthDate;
    }

    public function setBirthDate(?\DateTimeInterface $BirthDate): static
    {
        $this->BirthDate = $BirthDate;

        return $this;
    }

    /**
     * @return Collection<int, Weakness>
     */
    public function getWeaknesses(): Collection
    {
        return $this->weaknesses;
    }

    public function addWeakness(Weakness $weakness): static
    {
        if (!$this->weaknesses->contains($weakness)) {
            $this->weaknesses->add($weakness);
        }

        return $this;
    }

    public function removeWeakness(Weakness $weakness): static
    {
        $this->weaknesses->removeElement($weakness);

        return $this;
    }

    
}

templates/personajes/character.html.twig
{% extends "base.html.twig" %}

{% block body %}
<h2>El personaje con id {{id}} </h2>
<section>
    <div class="card" style="width: 18rem;">
        <img src="..." class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{character.name}}</h5>
          <p class="card-text">Descripción: {{character.description}}</p>
          <p class="card-text">Superpoder: {{character.superpower}}</p>
          <p class="card-text">Planeta: {{character.planet}}</p>
          <p class="card-text">Fecha de nacimiento: {{character.BirthDate|date("Y-m-d")}}</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
    <ul>Debilidades:
        {% for weakness in character.weaknesses %}
        <li>{{weakness.name}}</li>
            
        {% endfor %}
    </ul>
</section>
{% endblock %}
{% block footer %}
<h2>Footer</h2>
{% endblock %}

templates/personajes/createCharacter.html.twig
{% extends "base.html.twig" %}

{% block body %}

{{form(formCharacter)}}

{% endblock %}

{% block stylesheets %}
<style>
    .nameInput {
        background-color:aquamarine;
    }
</style>

{% endblock %}

templates/personajes/listCharacters.html.twig
{% extends "base.html.twig" %}

{% block body %}
{% for character in characters %}
<section>
    <h3>Nombre: {{character.name}}</h3>
    <p>Planeta: {{character.planet}}</p>
    <p>Superpoder: {{character.superpower}}</p>
    <p>Descripción: {{character.description}}</p>
    {% if character.BirthDate %}
    <p>Fecha de nacimiento: {{character.BirthDate|date("Y-m-d")}}</p>
    {% endif %}
    {% if is_granted("ROLE_ADMIN") %}
    <a href="{{path('detailcharacter', {'id': character.id})}}">Más informacion</a>
    <a href="{{path('edit', {'id': character.id})}}">Editar</a>
    {% endif %}

</section>
{% endfor %}
{% endblock %}

{% block aside %}
<aside> <h2>Publicidad</h2> </aside>
{% endblock %}